### ISSUE TITLE
Compile on Ubuntu fails: Renderer_draw_gl.cpp

### ISSUE THREAD

**Issue by cmcginty** [Aloshi/EmulationStation#675]
```home/panther/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:69: error: call of overloaded ‘round(float&)’ is ambiguous
   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
                                                                     ^
```

**Comment by meatballz** [comment]
I get that one too. Ubuntu 17.04 64-bit.

**Comment by tay10r** [comment]
same here, ubuntu 17.04 64-bit, gcc 6.3.0

**Comment by tay10r** [comment]
It looks like this problem is fixed in #666. Look at the preprocessor guard they put around the prototype and definition of the function. Those guards are all you have to add to get it working.

**Comment by djnice** [comment]
Please comment out the round function from /es-core/src/Util.cpp and /es-core/src/Util.h files, and will works on Ubuntu 17.04.

Util.h:
//float round(float num);

Util.cpp:
#if _MSC_VER < 1800
/*float round(float num)
{
	return (float)((int)(num + 0.5f));
}*/
#endif

**Comment by tay10r** [comment]
@djnice, the reason it's not commented out is because it's required for certain Windows bulls. it's not getting commented out, it won't need to be when the preprocessor expression is fixed.

**Comment by Funcron** [comment]
7 years later... getting the same error on Ubuntu 22, aarch64. commenting out the sections in util* seems to still work though.
