### ISSUE TITLE
Fails to compile using GCC 9.3.0

### ISSUE THREAD

**Issue by kcgen** [Aloshi/EmulationStation#831]
**Platform:** standard Ubuntu 20.04
**Compiler:** GCC 9.3.0

1. Copy & pasted instructions from the home page
2. Dependencies installed clean
3. git clone and cmake ran clean
4. Make fails here:

``` text
/usr/src/EmulationStation/es-core/src/Renderer_draw_gl.cpp: In function ‘void Renderer::drawRect(float, float, float, float, unsigned int, GLenum, GLenum)’:
/usr/src/EmulationStation/es-core/src/Renderer_draw_gl.cpp:90:24: error: call of overloaded ‘round(float&)’ is ambiguous
   90 |   drawRect((int)round(x), (int)round(y), (int)round(w), (int)round(h), color, blend_sfactor, blend_dfactor);
      |                        ^
In file included from /usr/include/features.h:461,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/9/bits/c++config.h:524,
                 from /usr/include/c++/9/string:38,
                 from /usr/src/EmulationStation/es-core/src/platform.h:18,
                 from /usr/src/EmulationStation/es-core/src/Renderer_draw_gl.cpp:1:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:298:1: note: candidate: ‘double round(double)’
```
